# ----------------------------------------------------
# CONFIGURACIÓN DE BASE DE DATOS POSTGRESQL (JDBC)
# ----------------------------------------------------
# URL de conexión: apunta a PostgreSQL en el puerto 5432 y la DB 'registro_partos'
spring.datasource.url=jdbc:postgresql://localhost:5432/registro_partos
spring.datasource.username=postgres
spring.datasource.password=Cony1606

# ----------------------------------------------------
# CONFIGURACIÓN DE JPA / HIBERNATE
# ----------------------------------------------------
# 'update': Hibernate actualiza el esquema de la base de datos (crea/modifica tablas)
# basado en las clases @Entity. ¡Debe cambiarse a 'validate' en producción!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Muestra las consultas SQL generadas por Hibernate en la consola
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ----------------------------------------------------
# CONFIGURACIÓN DEL SERVIDOR WEB EMBEBIDO
# ----------------------------------------------------
# El backend se ejecuta en este puerto (diferente del frontend 4200)
server.port=8080
